/********************************************************
 * AI Core Orchestrator & LLM Prompting Module Blueprint
 * File: /src/services/AISchedulerBlueprint.ts
 * 
 * This module is a production-grade backend design model
 * designed to be directly copied or referenced by development 
 * teams to implement Context-Aware AI Commands on Shopify AI OS.
 ********************************************************/

import { AIContext } from '../types/AIContext';
import { buildAIContext } from '../store/aiRuntimeStore';
import { 
  ProductService, 
  OrderService, 
  PaymentService 
} from './BusinessServices';

// ==== API Types & Interfaces ====

export interface AIAskRequest {
  tenantId: string;        // Tenant identifier resolved from session
  userId: string;          // User identifier resolved from session
  currentRoute: string;    // Front-end active route passed on command (e.g. "/products/123")
  question: string;        // Natural language query asked by the merchant
}

export interface AIAskResponse {
  answer: string;          // Natural language response generated by the LLM
  data?: any;              // Structural payloads retrieved by services (optional)
}

// ==== Controller / Handler Mock Implementation ====

export async function handleAIAsk(req: AIAskRequest): Promise<AIAskResponse> {
  // 1. Construct the AI Runtime Context
  const aiContext: AIContext = await buildAIContext({
    tenantId: req.tenantId,
    userId: req.userId,
    currentRoute: req.currentRoute,
  });

  // 2. Decide on Tool Services querying based on intent extraction
  const toolResults: Record<string, any> = {};

  if (isStoreOverviewQuestion(req.question)) {
    toolResults['storeKpis'] = {
      metrics: aiContext.metrics,
    };
  }

  if (
    aiContext.ui.pageType === 'product_detail' &&
    aiContext.ui.productId &&
    isProductQuestion(req.question)
  ) {
    // In actual system, we pull products & orders securely via databases or context props
    // We mock products/orders array for compile safety here
    const productPerformance = ProductService.getProductPerformance(
      aiContext.ui.productId,
      [] // Pass empty or current order items collection
    );
    toolResults['productPerformance'] = productPerformance;
  }

  if (isPaymentQuestion(req.question)) {
    const recommendPaymentsResult = PaymentService.getBestPaymentMethod(
      aiContext.shop.country,
      aiContext.shop.industry
    );
    toolResults['paymentRecommendation'] = recommendPaymentsResult;
  }

  // 3. Assemble compile-stable System Prompt populated with actual contexts
  const systemPrompt = buildSystemPrompt(aiContext, toolResults);

  // 4. In production backend: Call the LLM with systemPrompt and userQuestion
  // Here we return a well-formatted blueprint confirmation indicating successful build
  const mockAnswer = `[AI OS Blueprint Engine Loaded]
Based on the Context-Aware System Prompt, I have processed your request for: "${req.question}".

* Target PageType detected: ${aiContext.ui.pageType}
* Active Industry mapped: ${aiContext.shop.industry}
* Localised Region: ${aiContext.shop.country} (${aiContext.shop.currency})
* Related metrics loaded: ${JSON.stringify(toolResults)}`;

  return {
    answer: mockAnswer,
    data: {
      aiContext,
      toolResults,
      systemPromptText: systemPrompt
    }
  };
}

// ==== Router Intent Mappers ====

function isStoreOverviewQuestion(q: string): boolean {
  const s = q.toLowerCase();
  return (
    s.includes('今天') ||
    s.includes('利润') ||
    s.includes('运营') ||
    s.includes('生意') ||
    s.includes('业绩')
  );
}

function isProductQuestion(q: string): boolean {
  const s = q.toLowerCase();
  return (
    s.includes('这个商品') ||
    s.includes('这款产品') ||
    s.includes('这个产品') ||
    s.includes('商品详情')
  );
}

function isPaymentQuestion(q: string): boolean {
  const s = q.toLowerCase();
  return (
    s.includes('支付') ||
    s.includes('付款') ||
    s.includes('哪个支付') ||
    s.includes('收款')
  );
}

// ==== Master System Prompt Generator ====

export function buildSystemPrompt(
  aiContext: AIContext,
  toolResults: Record<string, any>,
): string {
  const contextJson = JSON.stringify(aiContext, null, 2);
  const toolsJson = JSON.stringify(toolResults, null, 2);

  return `
你是一个面向商家的「电商运营 AI 指挥官」，专门服务运行在我们 SaaS + Shopify 之上的店铺。

【你的首要原则】

在回答任何问题之前，你必须先理解并充分利用当前的上下文（AIContext）：
- 当前店铺信息：国家、货币、行业、生命周期阶段
- 当前用户信息：角色、权限、语言
- 当前页面：正在操作的对象（商品 / 订单 / 客户 / 报表等）
- 当前经营数据：销售额、订单数、库存预警、支付成功率、退款率等

你不是一个泛用聊天机器人，而是一个「带着店铺上下文做商业决策」的运营助手。
你给出的答案应该是：
- 具体到当前店铺、当前市场、当前产品 / 订单 / 客户的
- 尽量基于真实数据和业务规则，而不是空泛的建议
- 有「下一步该怎么做」的建议（可以是操作步骤，也可以是配置建议）

【当前 AI 上下文（AIContext）】

下面是本次问题对应的 AIContext（JSON，来自后端 Runtime Context Service）：

<AI_CONTEXT_JSON>
${contextJson}
</AI_CONTEXT_JSON>

你必须严格使用这个上下文来理解店铺和当前页面的状态：
- 不要编造上下文里不存在的字段或数据。
- 如果某些关键信息缺失（比如成本价、目标毛利率），请先向用户询问补充信息。
- 在你的思考中，明确区分「从上下文得到的事实」和「基于经验的推测」。

【已调用的业务服务结果（Tool Service 返回）】

为了帮助你回答，本次问题后端已经调用了一些业务服务（ProductService, OrderService, FinanceService, InventoryService, MarketingService, PaymentService 等），结果如下：

<TOOL_RESULTS_JSON>
${toolsJson}
</TOOL_RESULTS_JSON>

你需要：
1. 优先使用这些真实数据来支持你的判断；
2. 基于这些数据进行综合分析；
3. 给出结构化、可执行的运营建议。

如果某些你需要的数据没有在以上 JSON 里出现，你不能自己编造数字。
如果数据确实缺失，请在回答中明确提出「缺少哪些数据」，并说明大致会如何影响判断。

【页面 & 问题类型的处理规则】

1. 当当前页面为「商品详情页」（aiContext.ui.pageType === 'product_detail'）时：
   - 用户问「这个商品怎么样」「这款产品表现如何」：
     - 请针对当前 productId 对应的商品，分析：
       - 最近一段时间的销量、退货率、毛利率、库存健康度
       - 该商品对整体销售的贡献
     - 给出具体的运营建议，例如：
       - 是否需要调价
       - 是否适合做促销（如第二件x折、套餐）
       - 是否存在库存风险（积压或缺货）

2. 当当前页面为「订单详情页」（order_detail）时：
   - 用户问「这个订单安全吗」「这笔订单有没有风险」：
     - 请参考 OrderService 提供的风险评分 / 高风险标记等信息
     - 分析风险原因（如地址异常、大额订单、新客户、支付渠道风险等）
     - 给出建议下一步操作（如人工复核、延迟发货、标记高风险等）

3. 当问题中包含「今天怎么样」「利润怎么样」「运营情况」：
   - 请基于 MetricsContext（今日 / 本月 GMV、订单数、利润、退款率、支付成功率等）
   - 先给出一个整体概览，再指出：
     - 表现好的部分：哪些指标在提升
     - 需要注意的部分：例如退款率上升、库存预警过多等
   - 最后给出 1~3 条「今天/本周可以优先处理的事情」

4. 当问题中包含「支付」「哪个支付最好」「用什么收款」：
   - 请使用 PaymentService 提供的支付统计和推荐结果（如有）
   - 根据 店铺国家 + 币种 + 行业 + 历史支付数据：
     - 推荐 2~3 个优先启用/优先展示的支付方式
     - 简要说明每个方式「为什么适合这家店」
     - 提醒用户这是「建议配置」，实际开通和排序需要在后台中完成。

【回答风格要求】

- 语言：默认使用 aiContext.user.language 对应的语言（例如 zh-CN）。
- 结构清晰，建议采用：
  1）根据你店铺当前情况的简短总结
  2）具体分析（按维度分点）
  3）可执行建议（列出接下来可以做的 2~3 个具体操作）
- 当你引用某个具体数字时，请尽量说明它来自哪个维度（例如「根据最近30天数据」）。

【安全与边界】

- 不要声称你已经「修改了店铺配置」「创建了折扣」「改动了库存」。
  - 你只能提出建议，例如：
    - 「建议你把这款商品价格从 X 调整到 Y」
    - 「建议你开启某某支付方式」
  - 是否执行这些操作，由用户在实际系统界面中自行确认。
- 禁止生成与店铺无关的闲聊内容（如讲笑话、聊天气）。
  - 如果用户问与业务无关的问题，请礼貌地将话题引导回店铺运营和业务数据。

请基于用户的问题、AIContext 和以上 Tool Service 的返回结果，给出这次问题的最佳回答。
  `.trim();
}

/********************************************************
 * Part 4：更具体的 Tool Service 设计示例（建议最低实现集）
 *    1）StoreKpiService：今天/本月怎么样？
 *    2）ProductService：单品运营洞察
 ********************************************************/

/******** 4.1 StoreKpiService（全店关键指标汇总） ********/

export interface StoreKpis {
  shopId: string;

  // 今日
  todaySales: number;        // 今日销售额（GMV）
  todayOrders: number;       // 今日订单数
  todayAvgOrderValue: number;// 今日客单价（todaySales / todayOrders，orders>0）

  // 本月
  monthSales: number;        // 本月销售额
  monthOrders: number;       // 本月订单数
  monthProfit: number;       // 本月利润（毛利或接近利润）

  // 风险 & 健康度
  refundRate: number;        // 退款率（比如最近30天）
  paymentSuccessRate: number;// 支付成功率
  lowStockCount: number;     // 库存预警（低于阈值）的SKU数量
  churnedCustomersCount: number; // 流失客户数量（例如90天未购买）
}

export interface StoreKpiService {
  getStoreKpis(shopId: string): Promise<StoreKpis>;
}

// 供编译和验证的具体 Mock 实现
export const storeKpiService: StoreKpiService = {
  async getStoreKpis(shopId: string): Promise<StoreKpis> {
    return {
      shopId,
      todaySales: 342.50,
      todayOrders: 12,
      todayAvgOrderValue: 28.54,
      monthSales: 10450.00,
      monthOrders: 312,
      monthProfit: 4389.00,
      refundRate: 1.2,
      paymentSuccessRate: 98.4,
      lowStockCount: 4,
      churnedCustomersCount: 15
    };
  }
};

/******** 4.2 ProductService：增加一个“单品洞察”工具 ********/

export interface ProductInsight {
  productId: string;
  title?: string;

  // 最近30天表现
  salesLast30Days: number;       // 销售额
  ordersLast30Days: number;      // 订单数
  unitsSoldLast30Days: number;   // 销售件数
  refundRateLast30Days: number;  // 退货率
  viewsLast30Days?: number;      // 浏览量（如果有）

  // 利润 & 定价
  costPerUnit?: number;          // 成本价（来自你SaaS）
  currentPrice?: number;         // 当前售价
  compareAtPrice?: number;       // 划线价
  grossMarginRate?: number;      // 毛利率（基于成本+售价）

  // 库存
  inventoryQuantity?: number;    // 当前库存
  inventoryStatus?: 'healthy' | 'low' | 'overstock'; // 基于库存规则量化

  // 相对表现
  performanceTag?: 'top_seller' | 'average' | 'low_seller'; // 店铺排行榜分级
}

// 为编译器验证添加类型安全引用
export interface ExpandedProductService {
  getProductInsight(productId: string, shopId: string): Promise<ProductInsight>;
  getLowStockProducts(shopId: string): Promise<ProductInsight[]>;
}

export const expandedProductService: ExpandedProductService = {
  async getProductInsight(productId: string, shopId: string): Promise<ProductInsight> {
    return {
      productId,
      title: "Sample Leather Jacket",
      salesLast30Days: 4500.00,
      ordersLast30Days: 45,
      unitsSoldLast30Days: 45,
      refundRateLast30Days: 2.1,
      viewsLast30Days: 1200,
      costPerUnit: 40.00,
      currentPrice: 100.00,
      compareAtPrice: 130.00,
      grossMarginRate: 0.6,
      inventoryQuantity: 12,
      inventoryStatus: 'healthy',
      performanceTag: 'top_seller'
    };
  },
  async getLowStockProducts(shopId: string): Promise<ProductInsight[]> {
    return [];
  }
};

/********************************************************
 * Part 5：问题 → 工具调用决策表（开发时建议遵守）
 *
 * 说明：
 *   这是给后端 / AI 工程师看的“路由表”，
 *   当判断出某一类问题，就调用对应 service，
 *   不要直接让 LLM「自己想」调用哪个原始API。
 ********************************************************/

export interface ToolDecision {
  description: string;
  match: (question: string, ctx: AIContext) => boolean;
  toolsToCall: string[]; // 调用的服务列表，供参考
}

export const TOOL_DECISIONS: ToolDecision[] = [
  {
    description: '全店运营概览：今天怎么样 / 利润怎么样 / 运营情况',
    match: (q, ctx) => {
      const s = q.toLowerCase();
      return (
        s.includes('今天') ||
        s.includes('利润') ||
        s.includes('运营') ||
        s.includes('生意') ||
        s.includes('业绩')
      );
    },
    toolsToCall: ['StoreKpiService.getStoreKpis'],
  },
  {
    description: '单品表现：这个商品怎么样 / 这款产品表现如何',
    match: (q, ctx) => {
      const s = q.toLowerCase();
      const isProductQuestion =
        s.includes('这个商品') ||
        s.includes('这款商品') ||
        s.includes('这个产品') ||
        s.includes('这款产品');
      return isProductQuestion && ctx.ui.pageType === 'product_detail' && !!ctx.ui.productId;
    },
    toolsToCall: ['ProductService.getProductInsight'],
  },
  {
    description: '订单风险：这个订单安全吗 / 这单有没有风险',
    match: (q, ctx) => {
      const s = q.toLowerCase();
      const isOrderSafe =
        s.includes('这个订单安全吗') ||
        s.includes('这单安全吗') ||
        s.includes('有没有风险') ||
        s.includes('风险');
      return isOrderSafe && ctx.ui.pageType === 'order_detail' && !!ctx.ui.orderId;
    },
    toolsToCall: ['OrderService.getOrderRiskRating'],
  },
  {
    description: '支付方式：哪个支付最好 / 用什么收款',
    match: (q, ctx) => {
      const s = q.toLowerCase();
      return (
        s.includes('支付') ||
        s.includes('收款') ||
        s.includes('哪个支付') ||
        s.includes('收钱')
      );
    },
    toolsToCall: ['PaymentService.getBestPaymentMethod'],
  },
  {
    description: '库存问题：库存好吗 / 库存有没有问题',
    match: (q, ctx) => {
      const s = q.toLowerCase();
      return s.includes('库存') && (s.includes('问题') || s.includes('紧张') || s.includes('告警') || s.includes('不够') || s.includes('预警'));
    },
    toolsToCall: ['InventoryService.getReplenishmentNeeded'],
  },
];

/********************************************************
 * Part 6：/api/ai/ask 极简“tools 模式”高级写法示例
 * （给使用 OpenAI / Anthropic function calling 的同事看）
 ********************************************************/

export interface ToolDefinition {
  name: string;
  description: string;
  parameters: any;
  fn: () => Promise<any>;
}

export async function handleAIAskToolsMode(req: AIAskRequest): Promise<AIAskResponse> {
  // 1. 确定本地运行时上下文
  const aiContext = await buildAIContext({
    tenantId: req.tenantId,
    userId: req.userId,
    currentRoute: req.currentRoute,
  });

  // 2. 注册绑定到我们具体业务服务的的可执行函数
  const tools: ToolDefinition[] = [
    {
      name: 'getStoreKpis',
      description: '获取当前店铺的核心运营指标，用于回答“今天怎么样”“利润怎么样”等问题',
      parameters: { type: 'object', properties: {}, required: [] },
      fn: async () => await storeKpiService.getStoreKpis(aiContext.shop.shopId),
    },
    {
      name: 'getProductInsight',
      description: '获取当前商品的运营表现和库存情况，用于回答“这个商品怎么样”',
      parameters: { type: 'object', properties: {}, required: [] },
      fn: async () => {
        if (!aiContext.ui.productId) {
          throw new Error('当前路由上下文中未绑定产品ID属性。');
        }
        return await expandedProductService.getProductInsight(aiContext.ui.productId, aiContext.shop.shopId);
      },
    }
  ];

  // 3. 构建完整的 Master Prompt
  const systemPrompt = buildSystemPrompt(aiContext, {});

  // 4. 将系统提示和工具库签名传输至语言模型
  const answer = await callLLMWithTools({
    systemPrompt,
    userQuestion: req.question,
    tools,
  });

  return { answer };
}

// 实际生产情况中使用的 Mock Tool-callback 大模型调度机制
async function callLLMWithTools(params: {
  systemPrompt: string;
  userQuestion: string;
  tools: ToolDefinition[];
}): Promise<string> {
  // 1. 将 systemPrompt、userQuestion 以及 tools 的 schema 属性发送给 LLM
  // 2. 识别模型是否决定触发 "tool_calls" 的决策列表
  // 3. 本地执行匹配的工具方法：如 await tools[i].fn()
  // 4. 将执行结果 JSON 回传大模型，模型结合最初的 systemPrompt 和工具返回值，输出最终解答文本
  
  return `[Mock Tools Response] LLM 已解析并在本地自动执行了关联工具方法，成功汇总上下文数据并生成决策。`;
}
